# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - identifier: research
    name: "Research"
    url: "/research/"
    weight: 10
  - identifier: team
    name: "Team"
    url: "/team/"
    weight: 20
  - identifier: work
    name: "Work"
    url: "/work/"
    weight: 30
  - identifier: funding
    name: "Funding"
    url: "/funding/"
    weight: 40
  - identifier: join
    name: "Join"
    url: "/join/"
    weight: 50
