name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ "main" ]       # Builds on pushes to main
  workflow_dispatch:           # Allows manual trigger

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: "latest"
        extended: true

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
